-----BEGIN PGP SIGNED MESSAGE-----
Hash: SHA512

Backend build with dotnet.
-----BEGIN PGP SIGNATURE-----

iHUEARYKAB0WIQQbQqtxBkwLrI8IuMuDzq02WWBJ3gUCaUP1nwAKCRCDzq02WWBJ
3nJ/AP9xQkrlPfzIEhbjz2y/+FUNA0NYFprUstOGnF8ESbRmMQD+OHbsLAKfhqJT
yIIcCE7FwtovC8lbVETBybDY3fhMzgA=
=QmK0
-----END PGP SIGNATURE-----
